# Generated by Django 4.1 on 2023-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="questions.question"
            ),
        ),
    ]
