# Generated by Django 4.1 on 2023-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_tag_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="questions.question",
            ),
        ),
    ]
