# Generated by Django 4.1 on 2023-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_tag_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)ss",
                related_query_name="%(class)s",
                to="questions.tag",
            ),
        ),
    ]
