# Generated by Django 4.1 on 2023-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_remove_tag_questions_question_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=110, unique=True),
        ),
    ]
