# Generated by Django 4.1 on 2023-02-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_alter_answer_choices_alter_answer_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
