# Generated by Django 4.1 on 2023-02-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Choice",
                "verbose_name_plural": "Choice",
            },
        ),
    ]
