# Generated by Django 4.1 on 2023-02-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0011_alter_choice_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="published",
            new_name="is_published",
        ),
    ]
