# Generated by Django 4.1 on 2023-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0012_rename_published_question_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_multichoice",
            field=models.BooleanField(default=False),
        ),
    ]
